version: '3.9'

services:
  api-server:
    image: api-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10080:8080"

    volumes:
      - ./:/workspace
    tty: true
    command: /bin/bash
