version: '3.9'

services:
  # --------- API SERVER SETUP  ---------- #
  api-server:
    image: api-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10080:8080"

    volumes:
      - ./:/workspace
    tty: true
    command: /bin/bash
  # --------- Locust TEST SETUP ---------- #

  locust-metrics-exporter:
    image: containersol/locust_exporter
    ports:
      - "9646:9646"
    environment:
      - LOCUST_EXPORTER_URI=http://api-server:8089

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
  # --------- k6 TEST SETUP ---------- #
  influxdb:
    image: influxdb:latest
    networks:
      - k6
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
  grafana:
    image: grafana/grafana:latest
    networks:
      - grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
      - ./grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
  k6:
    image: loadimpact/k6:latest
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./scripts:/scripts
  # # ------------------- #
  # # DB SETUP 
  # # ------------------- #
  # postgres:
  #   image: cyberw/locust-timescale:6
  #   # ports:
  #   #   - "5432:5432"

  #   environment:
  #     - POSTGRES_PASSWORD=password
  #     - TIMESCALEDB_TELEMETRY=off
  #   volumes:
  #     - /mnt/data/prj/test/postgresql_data:/var/lib/postgresql/data

  # # ------------------- #
  # # GRAFANA SETUP 
  # # ------------------- #
  # grafana:
  #   image: grafana/grafana:8.1.3
  #   environment:
  #     GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "true"
  #     GF_AUTH_ANONYMOUS_ENABLED: "true"
  #     GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
  #     GF_AUTH_DISABLE_SIGNOUT_MENU: "true"
  #     GF_AUTH_DISABLE_LOGIN_FORM: "true"
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - /mnt/data/prj/test/grafana_data:/var/lib/grafana
