version: '3.9'

services:
  # --------- API SERVER SETUP  ---------- #
  api-server:
    image: api-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10080:8080"

  # --------- k6 TEST SETUP ---------- #
  prometheus:
    image: prom/prometheus:v2.45.0
    ports:
      - 9090:9090
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
      - --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./config/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro

  k6:
    image: loadimpact/k6:0.42.0
    depends_on:
      - api-server
      - prometheus
    ports:
      - "6565:6565"
    environment:
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
      - K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM=true
      # - K6_OUT=xk6-prometheus-rw
    volumes:
      - ./run_k6.js:/scripts/run_k6.js
    command: "run /scripts/run_k6.js -o experimental-prometheus-rw"

  # --------- grafana SETUP ---------- #
  grafana:
    image: grafana/grafana:10.0.1
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:

      - ./config/grafana/prometheus-remote:/etc/grafana/provisioning/
