version: '3.9'

services:

  # --------- k6 TEST SETUP ---------- #
  influxdb:
    image: influxdb:1.8.0
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  k6:
    image: loadimpact/k6:latest
    depends_on:
      - api-server
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./run_k6.js:/scripts/run_k6.js
    command: "run /scripts/run_k6.js"

  # --------- grafana SETUP ---------- #
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./config/grafana/influx/k6-load-testing-results_rev3.json:/var/lib/grafana/dashboards/k6-load-testing-results_rev3.json
      - ./config/grafana/influx/dashboards:/etc/grafana/provisioning/dashboards/
      - ./config/grafana/influx/datasources:/etc/grafana/provisioning/datasources/
